### ISSUE TITLE
Changed the path and the baseURL, still searching in img

### ISSUE THREAD

**Issue by Lloople** [spatie/laravel-glide#10]
Hi, first of all thanks for your package.

I published the config and modified it to adjust to my project, but when I inspect the HTML I see the glide is generating the URL pointing to `img`, also it can't process a `load('folder/img.jpg')`, it transforms to `folder%2Fimg.jpg`.

Do you know how can I solve those problems?

Thanks!

**Comment by Lloople** [comment]
Now the images appears correctly in the website, but without any transoformation. I tried with this code:

`src="{{url(urldecode(GlideImage::load($folder_name.'/'.$file)->modify(['w'=> 20, 'filt'=>'greyscale']))) }}"`

Also I needed to modify the `GlideImage.php:82`

`$urlBuilder = UrlBuilderFactory::create('uploads', $this->signKey);`

Don't know what can I do

**Comment by Sennik** [comment]
I am experiencing the same problem. images are located in many subdirectories under /public/files. The reference (urls) are maintained in my own cms: 

    files/headers/imagename.jpg, 
    files/gallery/imagename.jpg

etc.

url's need to be urldecoded at first to get the slashes back (I think the package should take care of that?). After urldecoding myself no cache file is written and the image are not visible.

This is what I get (after urldecoding):

    /img/public/files/image/headers/imagename?w=1200&amp;filt=greyscale&amp;s=484c683bcdffffa677540e9e99bf9707

I think /img/ is the reference for the package that there should be a cached version of the file? No cache file is written at all. The storage directory is writable.

This is a very promising package and I am eager to use it!

**Comment by MatthiasDeWinter** [comment]
Hi,

First of all, I fixed the issue where the baseURL wouldn't be used. (_version 2.0.1_)

For convenience I made a fresh [Laravel 5 project](https://www.dropbox.com/s/vo0ybk35vf6hveg/GlideExample.zip?dl=0) to demonstrate the different ways of using this package.

In _welcome.blade.php:42_ an image is generated on the fly.

```php
<img src="{{ GlideImage::load('images/files/header/testImage.jpg')
			->modify(['w'=> 400]) }}">							                                                            
```

There is __no need to _urldecode___ the generated URL's.
The _urlencode_ in our source code is used to allow file names containing special characters like a space.

In _welcomeController.php:32_ an image is loaded and modified, saved elsewhere and passed to the view.

_(Don't forget to use the alias where you use the package )_


```php
use GlideImage;
```

```php
$outputPath = base_path('public/images/outputfolder/second_image.jpg');

$glideImage = GlideImage::load('images/files/header/testImage.jpg', ['w' => '250' , 'filt' => 'greyscale'])
	->save($outputPath);
```

[Here is a link to the full project](https://www.dropbox.com/s/vo0ybk35vf6hveg/GlideExample.zip?dl=0) so you can run it yourself. _Don't forget to run composer install_.

Also note that saving and writing the cache files works without a hitch in the example.

If the problems persist or you run into new issues you can always link me your project and I will do my best to help you out!

Thanks for the feedback!

**Comment by Lloople** [comment]
Hi @MatthiasDeWinter,

Thanks for your help and time.

I ran your project in local and I get the same issue, maybe is something ahead with Windows? I'm experiencing issues with thephpleague/glide too (https://github.com/thephpleague/glide/issues/44)

This is a screen of the url generated:

![image](https://cloud.githubusercontent.com/assets/5665466/6649115/9b61dd78-c9e3-11e4-8c5a-86161486994b.png)


Hpe it can help you to find a solution for this.

**Comment by Sennik** [comment]
Sorry for my late response, been busy.

I am using it on a Linux Server but same problem here. My project is not on github yet. 
The encoded slash is easy to fix though, just urlencode the url parts, not the slashes:

    // In glideImage.php
    public function getURL()
    {
        $urlBuilder = UrlBuilderFactory::create($this->baseURL, $this->signKey);
        
        // explode, urlencode and implode again
        $path = implode('/', array_map('rawurlencode', explode('/', $this->imagePath)));
        return $urlBuilder->getUrl($path, $this->modificationParameters);

But... stil not working.

I also installed the GlideExample Laravel project which runs into this error (ran composer install, storage is writable):

    Exception thrown when handling an exception (ErrorException: iconv(): Detected an illegal character in input string)

    ErrorException in GlideImage.php line 105: file_put_contents(/var/www/GlideExample/app/differentOutputFolder/savedImage.jpg): failed to open stream: No such file or directory (View: /var/www/GlideExample/resources/views/welcome.blade.php)

I see what you are doing here, creating a modified image with a specified name in a specified directory and use that one instead of the original. I see that you use output paths in your controller and blade examples. That's not flexible enough for me.

**My own project again:**
What I expect to achieve is to glideImage the image in the blade template with parameters (size, crop) and create a temporary modified copy in the cache directory which is used in the webpage. Just like https://code.google.com/p/timthumb/ does. This ways CMS users can upload images without resizing and cropping them first.

I tried several things to get it to work but so far no image is shown and no cache file is written in the storage directory.

I like your approach and I really want to use it.

**Comment by Sennik** [comment]
**again:**

    {{GlideImage::load('files/image/headers/imgname.jpg')->modify(['w'=> 400, 'h'=> 200])}}

**Results in:**

    /img/files/image/headers/imgname.jpg?w=400&amp;h=200&amp;s=29c84217bf02a6b53449b11cf0051e62

What is the img/ (baseUrl) supposed to do? Is this the trigger?

**Comment by Lloople** [comment]
I can't have it working.

If I copy-paste the spatie folder from the @MatthiasDeWinter GlideExample project I still see the URLs with `%2F` instead of `/`.

If I install laravel-glide with the current updates I can see the URLs correctly, but It does not show the image, just a broken link. It generates this:

`http://localhost/canae/public/gimages/pages/red.jpg?w=50&filt=sepia&s=770d3b452a79cecdd5e226b7356b4a64`

And my images are in:

`C:\Users\David\www\canae\public\uploads`

This is my source path configuration:

```
    'source' => [
        'path' => base_path('public'),
    ],
```

And this is what I have in baseUrl:

`'baseURL' => 'uploads',`

So I don't know where the problem is. The GlideExample either shows the images.

Any help? Need this package as soon as possible :(

**Comment by MatthiasDeWinter** [comment]
Try pasting the URL of the generated image after your home URL and see what the output is.

I found the error usually pops up in doing this.

**Comment by lukepolo** [comment]
I am also having the same problems with it not catching the URL, going to work on it tonight

**Comment by lukepolo** [comment]
Ok so after some digging. I found that the request that was sending to the validateSignature would include the path of the image 

array:3 [▼
  "/img/lukepolo_v2/2_png" => ""
  "w" => "390"
  "s" => "6f5ad787dbc35cb09c7738686410ce37"
]

This then, would not match what we originally sent to the generate signature .

So I added inside the validateSignature :

$this->request->query->remove(key($this->request->all()));


Then everything seemed to work . Anyone else had this problem ?

**Comment by lukepolo** [comment]
Look at issue #27 if your getting invalid signature. Also you must have the images in the storage area otherwise yes the route will just route to the image (Silly mistake I was making)
